### ISSUE TITLE
[FE]FEAT] 갤러리 이미지 이상함

### ISSUE THREAD

**Issue by OhJeongHwan1** [hyundai-autoever-second-project-team4/Review-FE#147]
## 💻 Feature 설명
> 1개일 때 문제인 것 같습니다. 갤러리 이미지가 이상해요...

**Comment by yeon-dong** [comment]
![image](https://github.com/user-attachments/assets/7a34ae1e-d984-490e-94d4-22ad05ad67a0)
Warning: Received NaN for the `height` attribute. If this is expected, cast the value to a string. Error Component Stack
영화 id 345330
